```{r}
require(SASxport)
```

```{r}
library(foreign)
```
```{r}
install.packages('dplyr')
library('tidyverse')
```

```{r}
DEMO_I <- read.xport ("DEMO_I.xpt")
HIQ_I <- read.xport ("HIQ_I.xpt")
HOQ_I <- read.xport ("HOQ_I.xpt")
INQ_I <- read.xport ("INQ_I.xpt")
PAQ_I <- read.xport ("PAQ_I.xpt")
```


```{r}
#merge datasets together
nhanes_1 <- full_join (DEMO_I, HIQ_I, by = "SEQN")
```

```{r}
nhanes_2 <-full_join(nhanes_1, HOQ_I, by = "SEQN")
```

```{r}
nhanes_3 <- full_join (nhanes_2, INQ_I, by = "SEQN")
```

```{r}
nhanes_final <- full_join(nhanes_3, PAQ_I, by = "SEQN")
```

```{r}
#create a small data set with selected variables: sex, age, education, income, housing, insurance, mins of mPA
nhanes_small<-nhanes_final%>%
  select(RIAGENDR, RIDAGEYR,RIDRETH3, DMDEDUC2,DMDEDUC3,INDFMIN2, HOQ065,HIQ011, PAD675)
```

```{r}
#view data
summary(nhanes_small)
```

```{r}
nhanes_recoded<-nhanes_small%>%
  mutate(RIAGENDR = recode_factor(.x=RIAGENDR,
                                    `1`='Male',
                                    `2` = 'Female'))%>%
mutate(RIDRETH3 = recode_factor(.x=RIDRETH3,
                                `1`= 'Hispanic',
                                `2`= 'Hispanic',
                                `3` = 'None-Hispanic White',
                                `4` = 'None-Hispanice Black',
                                `6` = 'Non-Hispanic Asian',
                                `7` = 'Other Race-Including Multi-racial'))%>%
mutate(DMDEDUC2 = recode_factor(.x=DMDEDUC2,
                                `1` = 'Less than 9th grade',
                                `2`='9-11th grade (Includes 12th grade with no diploma)', 
                                `3`='High school graduate/GED or equivalent', 
                                `4`= 'Some college or AA degree',
                                `5`= 'College graduate or above',
                                `7`= NA_character_,  
                                `9`= NA_character_))%>%
mutate(DMDEDUC3 = recode_factor(.x=DMDEDUC3,
                                `0`= 'Never attended school', 
                                `1`= 'Less than 9th grade',
                                `2`= 'Less than 9th grade',
                                `3`= 'Less than 9th grade',
                                `4`= 'Less than 9th grade',
                                `5`= 'Less than 9th grade',
                                `6`= 'Less than 9th grade',
                                `7`= 'Less than 9th grade',
                                `8`= 'Less than 9th grade',
                                `9`= '9-11th grade (Includes 12th grade with no diploma)',
                                `10`= '9-11th grade (Includes 12th grade with no diploma)',
                                `11`= '9-11th grade (Includes 12th grade with no diploma)',
                                `12`= '9-11th grade (Includes 12th grade with no diploma)',
                                `13`= 'High school graduate/GED or equivalent',
                                `14`= 'High school graduate/GED or equivalent',
                                `15`= 'High school graduate/GED or equivalent',
                                `55`= 'Less than 9th grade',
                                `66`= 'Less than 9th grade',
                                `77`= NA_character_, 
                                `99`= NA_character_))%>%
mutate(INDFMIN2=recode_factor(.x=INDFMIN2,
                                `1` = '<$20,000',
                                `2` = '<$20,000',
                                `3` = '<$20,000',
                                `4` = '<$20,000',
                                `5`= '$20,000-$99,999',
                                `6` = '$20,000-$99,999',
                                `7` ='$20,000-$99,999',
                                `8` ='$20,000-$99,999',
                                `9` ='$20,000-$99,999',
                                `10` = '$20,000-$99,999',
                                `12` = '$20,000-$99,999',
                                `13` = '<$20,000',
                                `14` = '$20,000-$99,999',
                                `15` = '$100,000 +',
                                `77` = NA_character_,
                                `99` =NA_character_ ))%>%
mutate(HOQ065 = recode_factor(.x=HOQ065,
                              `1` = 'Owned or bought',
                              `2` = 'Rented',
                              `3` = 'Other arrangement',
                              `7`= NA_character_,  
                              `9`= NA_character_))%>%
mutate(HIQ011 = recode_factor(.x =HIQ011,
                              `1` = 'Yes',
                              `2` = 'No',
                              `7`= NA_character_,  
                              `9`= NA_character_))%>%
mutate(PAD675= na_if(x=PAD675, y=9999))%>%
mutate(PAD675= na_if(x=PAD675, y=7777))%>% 
rename(sex = RIAGENDR) %>%
rename(race.eth = RIDRETH3) %>%
rename(adult.ed = DMDEDUC2) %>%
rename(child.ed = DMDEDUC3) %>%
rename(home.owned = HOQ065) %>%
rename(health.ins = HIQ011) %>%
rename(fam.annual.income = INDFMIN2)%>%
rename(age = RIDAGEYR)%>%
rename(mPA = PAD675)
```

```{r}
summary(nhanes_recoded)
```

